-- Keep the WhatsApp invitation message focused on one personal invitation link
-- and make the public RSVP table explicit in this Supabase project.
UPDATE public.invitation_message_templates
SET
  message_template = E'Assalamu''alaikum Bapak/Ibu {{nama_tamu}},\n\nTanpa mengurangi rasa hormat, perkenankan kami mengundang Bapak/Ibu/Saudara/i, teman sekaligus sahabat, untuk menghadiri acara pernikahan kami.\nBerikut link undangan kami, untuk info lengkap dari acara, bisa kunjungi :\n{{invitation_url}}\n\nMerupakan suatu kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan untuk hadir dan memberikan doa restu.\n\nWassalamualaikum Warahmatullahi Wabarakatuh\n\n\nQR code pada pesan ini digunakan untuk proses check-in di lokasi acara, harap save QR code ini.\n\nSalam,\nAnisa & Maulana',
  updated_at = now();

CREATE TABLE IF NOT EXISTS public.rsvps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 2 AND 80),
  guests INTEGER NOT NULL DEFAULT 1,
  attendance TEXT NOT NULL CHECK (attendance IN ('hadir', 'tidak')),
  message TEXT NOT NULL DEFAULT '' CHECK (char_length(message) <= 500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.rsvps ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  FOR constraint_name IN
    SELECT con.conname
    FROM pg_constraint AS con
    JOIN pg_class AS rel ON rel.oid = con.conrelid
    JOIN pg_namespace AS nsp ON nsp.oid = rel.relnamespace
    WHERE nsp.nspname = 'public'
      AND rel.relname = 'rsvps'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%guests%'
  LOOP
    EXECUTE format('ALTER TABLE public.rsvps DROP CONSTRAINT IF EXISTS %I', constraint_name);
  END LOOP;
END;
$$;

ALTER TABLE public.rsvps
  ADD CONSTRAINT rsvps_guests_between_1_and_2
  CHECK (guests BETWEEN 1 AND 2);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'rsvps'
      AND policyname = 'Public can read wedding wishes'
  ) THEN
    CREATE POLICY "Public can read wedding wishes"
      ON public.rsvps
      FOR SELECT
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'rsvps'
      AND policyname = 'Public can submit wedding RSVP'
  ) THEN
    CREATE POLICY "Public can submit wedding RSVP"
      ON public.rsvps
      FOR INSERT
      WITH CHECK (true);
  END IF;
END;
$$;

GRANT SELECT, INSERT ON public.rsvps TO anon, authenticated;
