apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-absen
  labels:
    app: wedding-absen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wedding-absen
  template:
    metadata:
      labels:
        app: wedding-absen
    spec:
      containers:
      - name: wedding-absen
        image: maulanamalik/public-image:invitation-wedding-qr-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: wedding-absen-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: wedding-absen-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: wedding-absen
