#!/bin/sh

ENV_FILE="/usr/share/nginx/html/env.js"

echo "window.env = {" > $ENV_FILE
echo "  VITE_SUPABASE_URL: \"${VITE_SUPABASE_URL}\"," >> $ENV_FILE
echo "  VITE_SUPABASE_PUBLISHABLE_KEY: \"${VITE_SUPABASE_PUBLISHABLE_KEY}\"," >> $ENV_FILE
echo "  VITE_SUPABASE_STORAGE_ENDPOINT: \"${VITE_SUPABASE_STORAGE_ENDPOINT}\"," >> $ENV_FILE
echo "  VITE_S3_ACCESS_KEY_ID: \"${VITE_S3_ACCESS_KEY_ID}\"," >> $ENV_FILE
echo "  VITE_S3_SECRET_ACCESS_KEY: \"${VITE_S3_SECRET_ACCESS_KEY}\"," >> $ENV_FILE
echo "  VITE_S3_REGION: \"${VITE_S3_REGION}\"," >> $ENV_FILE
echo "  VITE_ADMIN_USERNAME: \"${VITE_ADMIN_USERNAME}\"," >> $ENV_FILE
echo "  VITE_ADMIN_PASSWORD: \"${VITE_ADMIN_PASSWORD}\"" >> $ENV_FILE
echo "};" >> $ENV_FILE
