create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 80),
  guests integer not null default 1 check (guests between 1 and 5),
  attendance text not null check (attendance in ('hadir', 'tidak')),
  message text not null default '' check (char_length(message) <= 500),
  created_at timestamptz not null default now()
);

alter table public.rsvps enable row level security;
create policy "Public can read wedding wishes" on public.rsvps for select using (true);
create policy "Public can submit wedding RSVP" on public.rsvps for insert with check (true);
